export const BAVLI_TRACTATES_HEB_TO_CANONICAL: Record<string, string> = {
  "ברכות": "Berakhot",
  "שבת": "Shabbat",
  "פסחים": "Pesachim",
  "ביצה": "Beitzah",
  "סנהדרין": "Sanhedrin",
  "יומא": "Yoma",
  "מגילה": "Megillah",
  "תענית": "Taanit",
  "ראש השנה": "Rosh Hashanah",
  "מועד קטן": "Moed Katan",
  "חגיגה": "Chagigah",
  "גיטין": "Gittin",
  "קידושין": "Kiddushin",
  "בבא קמא": "Bava Kamma",
  "בבא מציעא": "Bava Metzia",
  "בבא בתרא": "Bava Batra",
  "שבועות": "Shevuot",
  "מכות": "Makkot",
};
