export const MISHNAH_TRACTATES_HEB_TO_CANONICAL: Record<string, string> = {
  "ברכות": "Berakhot",
  "פאה": "Peah",
  "דמאי": "Demai",
  "כלאים": "Kilayim",
  "שביעית": "Sheviit",
  "תרומות": "Terumot",
  "מעשרות": "Maasrot",
  "מעשר שני": "Maaser Sheni",
  "חלה": "Challah",
  "ערלה": "Orlah",
  "בכורים": "Bikkurim",
  "שבת": "Shabbat",
  "עירובין": "Eruvin",
  "פסחים": "Pesachim",
  "שקלים": "Shekalim",
  "יומא": "Yoma",
  "סוכה": "Sukkah",
  "ביצה": "Beitzah",
  "ראש השנה": "Rosh Hashanah",
  "תענית": "Taanit",
  "מגילה": "Megillah",
  "מועד קטן": "Moed Katan",
  "חגיגה": "Chagigah",
  "יבמות": "Yevamot",
  "כתובות": "Ketubot",
  "נדרים": "Nedarim",
  "נזיר": "Nazir",
  "סוטה": "Sotah",
  "גיטין": "Gittin",
  "קידושין": "Kiddushin",
  "בבא קמא": "Bava Kamma",
  "בבא מציעא": "Bava Metzia",
  "בבא בתרא": "Bava Batra",
  "סנהדרין": "Sanhedrin",
  "מכות": "Makkot",
  "שבועות": "Shevuot",
  "עדיות": "Eduyot",
  "עבודה זרה": "Avodah Zarah",
  "אבות": "Avot",
  "הוריות": "Horayot",
  "זבחים": "Zevachim",
  "מנחות": "Menachot",
  "חולין": "Chullin",
  "בכורות": "Bechorot",
  "ערכין": "Arakhin",
  "תמורה": "Temurah",
  "כריתות": "Keritot",
  "מעילה": "Meilah",
  "תמיד": "Tamid",
  "מידות": "Middot",
  "קינים": "Kinnim",
  "כלים": "Kelim",
  "אהלות": "Oholot",
  "נגעים": "Negaim",
  "פרה": "Parah",
  "טבול יום": "Tevul Yom",
  "ידים": "Yadayim",
  "עוקצים": "Uktzin",
  "מקוואות": "Mikvaot",
  "נזיקין": "Nezikin",
  "טהרות": "Taharot",
  "ביכורים": "Bikkurim",
};
