export const PREFIX_LETTERS = ["", "ו", "ב", "כ", "ל", "מ", "ה"] as const;

export const DEFAULT_LIMITS = {
  EXACT_REF_MAX_RESULTS: 10,
  EXACT_REF_MAX_SEGMENTS: 40,
  WORD_OCCURRENCES_MAX_RESULTS: 20,
  QUOTE_ENTITY_MAX_RESULTS: 30,
  LIST_WORKS_MAX_RESULTS: 100,
  CHAPTER_ABOUT_MAX_RESULTS: 50,
  CHAPTER_ABOUT_MAX_SEGMENTS: 80,
  GENERAL_QA_TOP_K: 8,
};
